spring:
  application:
    name: api-gateway-service

  cloud:
    gateway:
      routes:
      - id: user-service
        uri: http://localhost:9001/
        predicates:
        - Path=/userapp/**
        filters:
        - StripPrefix=1
      - id: choco-service
        uri: http://localhost:9002/
        predicates:
        - Path=/chocoapp/**
        filters:
        - StripPrefix=1
      - id: order-service
        uri: http://localhost:9003/
        predicates:
        - Path=/orderapp/**
        filters:
        - StripPrefix=1
        
server:
  port: 9000
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: false
